"""国风华容道 — 主题数据（服务端版本）"""

THEMES = [
    {
        'id': 'architecture', 'name': '传统建筑', 'shortDesc': '华夏建筑 · 匠心营造',
        'icon': '🏯',
        'subTopics': [
            {'id': 'potala-palace', 'name': '布达拉宫', 'icon': '🏰', 'desc': '西藏拉萨，世界屋脊上的宫殿'},
            {'id': 'stilted-house', 'name': '吊脚楼', 'icon': '🏚️', 'desc': '苗族传统民居，依山而建'},
            {'id': 'taihe-dian', 'name': '故宫太和殿', 'icon': '👑', 'desc': '紫禁城最高大的建筑，俗称金銮殿'},
            {'id': 'jiangnan-watertown', 'name': '江南水乡', 'icon': '🛶', 'desc': '小桥流水人家的江南古镇'},
            {'id': 'suzhou-garden', 'name': '苏州园林', 'icon': '🌿', 'desc': '咫尺之内再造乾坤'},
            {'id': 'tiantan', 'name': '天坛祈年殿', 'icon': '🙏', 'desc': '明清皇帝祭天的神圣场所'},
            {'id': 'tulou', 'name': '土楼', 'icon': '🟤', 'desc': '福建客家圆形土堡式民居'},
            {'id': 'summer-palace', 'name': '颐和园', 'icon': '⛲', 'desc': '中国现存最大的皇家园林'},
            {'id': 'great-wall', 'name': '长城', 'icon': '🧱', 'desc': '万里长城，中华民族的脊梁'},
        ],
    },
    {
        'id': 'festival', 'name': '传统节日与民俗', 'shortDesc': '岁时节庆 · 民俗风情',
        'icon': '🏮',
        'subTopics': [
            {'id': 'spring-festival', 'name': '春节', 'icon': '🧧', 'desc': '农历新年最隆重的传统佳节'},
            {'id': 'dragon-boat', 'name': '端午节', 'icon': '🐉', 'desc': '赛龙舟吃粽子，纪念屈原'},
            {'id': 'temple-fair', 'name': '逛庙会', 'icon': '🎪', 'desc': '热闹非凡的传统民俗盛会'},
            {'id': 'torch-festival', 'name': '火把节', 'icon': '🔥', 'desc': '彝族庆祝丰收祈福的传统节日'},
            {'id': 'water-festival', 'name': '泼水节', 'icon': '💦', 'desc': '傣族新年泼水送祝福'},
            {'id': 'dragon-lion', 'name': '舞龙舞狮', 'icon': '🦁', 'desc': '传统表演寓意驱邪迎祥'},
            {'id': 'lantern-festival', 'name': '元宵节', 'icon': '🏮', 'desc': '正月十五赏花灯吃元宵'},
            {'id': 'mid-autumn', 'name': '中秋节', 'icon': '🌕', 'desc': '赏月吃月饼阖家团圆'},
            {'id': 'double-ninth', 'name': '重阳节', 'icon': '🌺', 'desc': '登高望远赏菊敬老'},
        ],
    },
    {
        'id': 'art-opera', 'name': '传统艺术与戏曲', 'shortDesc': '梨园春秋 · 艺韵流芳',
        'icon': '🎭',
        'subTopics': [
            {'id': 'face-changing', 'name': '川剧变脸', 'icon': '🎭', 'desc': '瞬息之间变换多张脸谱'},
            {'id': 'dunhuang-art', 'name': '敦煌壁画', 'icon': '🎨', 'desc': '莫高窟飞天与佛教艺术'},
            {'id': 'erhu', 'name': '二胡', 'icon': '🎻', 'desc': '传统拉弦乐器音色悠扬婉转'},
            {'id': 'flower-bird', 'name': '工笔花鸟画', 'icon': '🌸', 'desc': '精细描绘花鸟虫鱼的技法'},
            {'id': 'guzheng', 'name': '古筝', 'icon': '🎶', 'desc': '传统弹拨乐器余音绕梁'},
            {'id': 'huangmei', 'name': '黄梅戏', 'icon': '🎵', 'desc': '安徽地方戏曲天仙配'},
            {'id': 'beijing-opera', 'name': '京剧', 'icon': '🎪', 'desc': '国粹京剧唱念做打集大成'},
            {'id': 'kunqu', 'name': '昆曲', 'icon': '🎼', 'desc': '百戏之祖最古老戏曲剧种'},
            {'id': 'pipa', 'name': '琵琶', 'icon': '🪕', 'desc': '大珠小珠落玉盘的弹拨乐'},
            {'id': 'landscape', 'name': '山水画', 'icon': '🏔️', 'desc': '水墨山水意境悠远'},
            {'id': 'yue-opera', 'name': '粤剧', 'icon': '🎤', 'desc': '广东地方戏曲瑰宝'},
        ],
    },
    {
        'id': 'intangible', 'name': '非遗与传统工艺', 'shortDesc': '匠心传承 · 巧夺天工',
        'icon': '🏺',
        'subTopics': [
            {'id': 'embroidery', 'name': '刺绣', 'icon': '🧵', 'desc': '以针为笔以线为墨'},
            {'id': 'paper-cut', 'name': '剪纸', 'icon': '✂️', 'desc': '红纸剪出吉祥如意图案'},
            {'id': 'facial-mask', 'name': '脸谱', 'icon': '👺', 'desc': '色彩图案展现人物性格'},
            {'id': 'shadow-play', 'name': '皮影', 'icon': '🎬', 'desc': '光影中的古老戏剧艺术'},
            {'id': 'blue-porcelain', 'name': '青花瓷', 'icon': '🫖', 'desc': '白釉青花中国瓷器经典'},
            {'id': 'bronze-ware', 'name': '青铜器', 'icon': '🔔', 'desc': '夏商周青铜礼器'},
            {'id': 'tang-sancai', 'name': '唐三彩', 'icon': '🏺', 'desc': '唐代三彩釉陶色彩绚丽'},
            {'id': 'sugar-painting', 'name': '糖画', 'icon': '🍭', 'desc': '以糖为墨的民间手艺'},
        ],
    },
    {
        'id': 'mythology', 'name': '神话传说与历史故事', 'shortDesc': '神话传说 · 历史典故',
        'icon': '🐉',
        'subTopics': [
            {'id': 'change-fly', 'name': '嫦娥奔月', 'icon': '🌙', 'desc': '嫦娥服仙丹飞向月宫'},
            {'id': 'monkey-king', 'name': '大闹天宫', 'icon': '🐒', 'desc': '孙悟空反抗权威的英雄故事'},
            {'id': 'apology', 'name': '负荆请罪', 'icon': '🌿', 'desc': '廉颇向蔺相如知错能改'},
            {'id': 'houyi-shoot', 'name': '后羿射日', 'icon': '🏹', 'desc': '射下九个太阳拯救苍生'},
            {'id': 'jingwei', 'name': '精卫填海', 'icon': '🐦', 'desc': '精卫衔石填海坚韧不拔'},
            {'id': 'kong-rong', 'name': '孔融让梨', 'icon': '🍐', 'desc': '四岁让梨谦让友爱的美德'},
            {'id': 'cowherd-weaver', 'name': '牛郎织女', 'icon': '💫', 'desc': '鹊桥相会七夕的来源'},
            {'id': 'nuwa', 'name': '女娲补天', 'icon': '🌈', 'desc': '炼石补天的创世神话'},
            {'id': 'pangu', 'name': '盘古开天', 'icon': '🌍', 'desc': '开天辟地万物之源'},
            {'id': 'sima-guang', 'name': '司马光砸缸', 'icon': '🪨', 'desc': '砸缸救人沉着冷静'},
        ],
    },
    {
        'id': 'food-clothing', 'name': '饮食与服饰文化', 'shortDesc': '舌尖中国 · 衣冠风华',
        'icon': '👘',
        'subTopics': [
            {'id': 'jiaozi', 'name': '饺子', 'icon': '🥟', 'desc': '春节必备形似元宝寓意吉祥'},
            {'id': 'mooncake', 'name': '月饼', 'icon': '🥮', 'desc': '中秋糕点代表团圆与思念'},
            {'id': 'zongzi', 'name': '粽子', 'icon': '🫔', 'desc': '端午糯米粽叶包裹的记忆'},
            {'id': 'tanghulu', 'name': '糖葫芦', 'icon': '🍡', 'desc': '酸甜可口的传统童年味道'},
            {'id': 'tangyuan', 'name': '汤圆', 'icon': '🍡', 'desc': '元宵传统美食象征团圆'},
            {'id': 'manhan-feast', 'name': '满汉全席', 'icon': '🍽️', 'desc': '清代宫廷盛宴极致体现'},
            {'id': 'hanfu-ruqun', 'name': '汉服襦裙', 'icon': '👗', 'desc': '汉族传统女子上衣下裙'},
            {'id': 'hanfu-quju', 'name': '汉服曲裾', 'icon': '👘', 'desc': '汉代深衣交领右衽礼服'},
            {'id': 'tang-suit', 'name': '唐装', 'icon': '🥋', 'desc': '唐代风格立领对襟典雅'},
            {'id': 'qipao', 'name': '旗袍', 'icon': '👘', 'desc': '东方女性之美的经典服饰'},
            {'id': 'miao-costume', 'name': '苗族服饰', 'icon': '👚', 'desc': '银饰刺绣绚丽多彩'},
            {'id': 'tibetan-costume', 'name': '藏族服饰', 'icon': '🧥', 'desc': '高原特色的鲜明服饰'},
            {'id': 'mongolian-costume', 'name': '蒙古族服饰', 'icon': '🦺', 'desc': '草原民族的文化标识'},
            {'id': 'hairpin', 'name': '发簪', 'icon': '📌', 'desc': '精美手工传统发饰'},
            {'id': 'jade-pendant', 'name': '玉佩', 'icon': '💎', 'desc': '君子佩玉传统玉文化'},
            {'id': 'sachet', 'name': '香囊', 'icon': '🎐', 'desc': '刺绣精美内含草药香料'},
            {'id': 'tiger-shoes', 'name': '虎头鞋', 'icon': '👟', 'desc': '虎头造型辟邪保平安'},
        ],
    },
    {
        'id': 'nature', 'name': '自然与风物文化', 'shortDesc': '锦绣山河 · 物华天宝',
        'icon': '🏔️',
        'subTopics': [
            {'id': 'huangshan', 'name': '黄山', 'icon': '⛰️', 'desc': '天下第一奇山奇松怪石'},
            {'id': 'guilin', 'name': '桂林山水', 'icon': '🏞️', 'desc': '桂林山水甲天下'},
            {'id': 'west-lake', 'name': '西湖', 'icon': '🌊', 'desc': '淡妆浓抹总相宜'},
            {'id': 'zhangjiajie', 'name': '张家界', 'icon': '🏔️', 'desc': '峰林奇观悬浮仙境'},
            {'id': 'jiuzhaigou', 'name': '九寨沟', 'icon': '💧', 'desc': '五彩池人间瑶池'},
            {'id': 'meilan-zhuju', 'name': '梅兰竹菊', 'icon': '🌸', 'desc': '花中四君子高洁品格'},
            {'id': 'peony', 'name': '牡丹', 'icon': '🌺', 'desc': '唯有牡丹真国色'},
            {'id': 'lotus', 'name': '荷花', 'icon': '🪷', 'desc': '出淤泥而不染君子之花'},
            {'id': 'koi', 'name': '锦鲤', 'icon': '🐟', 'desc': '寓意好运与成功'},
            {'id': 'crane', 'name': '仙鹤', 'icon': '🦩', 'desc': '象征长寿与吉祥'},
            {'id': 'tea', 'name': '茶叶', 'icon': '🍵', 'desc': '中国茶文化源远流长'},
            {'id': 'silk', 'name': '丝绸', 'icon': '🧣', 'desc': '丝绸之路的文化使者'},
            {'id': 'porcelain', 'name': '瓷器', 'icon': '🫖', 'desc': '景德镇千年窑火'},
            {'id': 'wenfang-sibao', 'name': '文房四宝', 'icon': '🖌️', 'desc': '笔墨纸砚文人之宝'},
        ],
    },
]

DIFFICULTIES = {
    3: {'size': 3, 'label': '入门', 'timeLimit': 180, 'moveLimit': 150, 'basePoints': 300},
    4: {'size': 4, 'label': '进阶', 'timeLimit': 360, 'moveLimit': 260, 'basePoints': 500},
}

REWARDS = [
    {'id': 'beginner', 'name': '初入江湖', 'icon': '🌟', 'points': 500, 'desc': '累计获得500积分'},
    {'id': 'enthusiast', 'name': '文化爱好者', 'icon': '📚', 'points': 1500, 'desc': '累计获得1500积分'},
    {'id': 'explorer', 'name': '文化探索者', 'icon': '🔍', 'points': 3000, 'desc': '累计获得3000积分'},
    {'id': 'scholar', 'name': '国学达人', 'icon': '🎓', 'points': 6000, 'desc': '累计获得6000积分'},
    {'id': 'master', 'name': '国风大师', 'icon': '🏅', 'points': 10000, 'desc': '累计获得10000积分'},
    {'id': 'legend', 'name': '文化传承者', 'icon': '👑', 'points': 20000, 'desc': '累计获得20000积分'},
]
