# Generated by Django 6.0.5 on 2026-05-27 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.CharField(max_length=50, verbose_name='主题ID')),
                ('theme_name', models.CharField(max_length=100, verbose_name='主题名称')),
                ('subtopic_id', models.CharField(max_length=50, verbose_name='子主题ID')),
                ('subtopic_name', models.CharField(max_length=100, verbose_name='子主题名称')),
                ('difficulty', models.IntegerField(verbose_name='难度')),
                ('time_spent', models.IntegerField(verbose_name='用时')),
                ('moves', models.IntegerField(verbose_name='步数')),
                ('hints_used', models.IntegerField(default=0, verbose_name='提示次数')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏记录',
                'verbose_name_plural': '游戏记录',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('total_points', models.IntegerField(default=0, verbose_name='总积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='EarnedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_id', models.CharField(max_length=50, verbose_name='徽章ID')),
                ('reward_name', models.CharField(max_length=100, verbose_name='徽章名称')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_rewards', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '已获徽章',
                'verbose_name_plural': '已获徽章',
                'unique_together': {('user', 'reward_id')},
            },
        ),
    ]
