# Generated by Django 6.0.5 on 2026-05-27 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.CharField(max_length=50)),
                ('theme_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('time_seconds', models.IntegerField()),
                ('moves', models.IntegerField()),
                ('hints_used', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar', models.CharField(default='🧩', max_length=10, verbose_name='头像')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='音效')),
                ('animation_enabled', models.BooleanField(default=True, verbose_name='动画')),
                ('highlight_enabled', models.BooleanField(default=True, verbose_name='高亮提示')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
