# Generated by Django 6.0.5 on 2026-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=100, verbose_name='主题名称')),
                ('item_name', models.CharField(max_length=100, verbose_name='条目名称')),
                ('title', models.CharField(max_length=200, verbose_name='展示标题')),
                ('content', models.TextField(verbose_name='文化介绍')),
            ],
            options={
                'verbose_name': '文化知识',
                'verbose_name_plural': '文化知识',
                'unique_together': {('theme_name', 'item_name')},
            },
        ),
    ]
