THEMES = [
    {
        'id': 'architecture',
        'name': '传统建筑',
        'icon': '🏯',
        'color': '#c41e3a',
        'bg_gradient': 'linear-gradient(135deg, #2d1b1b, #4a2020)',
        'description': '探索中华传统建筑的宏伟与精妙，感受千年营造智慧。',
        'items': [
            {'id': 'budala', 'name': '布达拉宫', 'desc': '西藏拉萨的宫堡式建筑群，藏传佛教圣地。'},
            {'id': 'diaojiao', 'name': '吊脚楼', 'desc': '南方少数民族的传统民居，依山傍水而建。'},
            {'id': 'taihe', 'name': '故宫太和殿', 'desc': '北京故宫最大的宫殿，明清皇帝举行大典之所。'},
            {'id': 'jiangnan', 'name': '江南水乡', 'desc': '小桥流水人家，粉墙黛瓦的江南韵味。'},
            {'id': 'suzhouyuanlin', 'name': '苏州园林', 'desc': '咫尺之内再造乾坤，中国园林艺术的典范。'},
            {'id': 'tiantan', 'name': '天坛祈年殿', 'desc': '明清帝王祭天祈谷的庄严场所。'},
            {'id': 'tulou', 'name': '土楼', 'desc': '福建客家独特的圆形聚居建筑，世界文化遗产。'},
            {'id': 'yiheyuan', 'name': '颐和园', 'desc': '中国现存最大的皇家园林，湖光山色美不胜收。'},
            {'id': 'greatwall', 'name': '长城', 'desc': '万里长城，中华民族的象征与骄傲。'},
        ],
    },
    {
        'id': 'festivals',
        'name': '传统节日与民俗',
        'icon': '🏮',
        'color': '#e8481e',
        'bg_gradient': 'linear-gradient(135deg, #2d1b0e, #4a2810)',
        'description': '走进热闹的传统节日，体验丰富多彩的民俗文化。',
        'items': [
            {'id': 'chunjie', 'name': '春节', 'desc': '中华民族最隆重的传统佳节，辞旧迎新、阖家团圆。'},
            {'id': 'duanwu', 'name': '端午节', 'desc': '赛龙舟、吃粽子，纪念爱国诗人屈原。'},
            {'id': 'miaohui', 'name': '逛庙会', 'desc': '春节期间的民间集市，舞龙舞狮、杂耍小吃。'},
            {'id': 'huoba', 'name': '火把节', 'desc': '彝族等少数民族的火之庆典，载歌载舞。'},
            {'id': 'poshui', 'name': '泼水节', 'desc': '傣族新年，互相泼水祝福，洗涤过去迎接新生。'},
            {'id': 'wushi', 'name': '舞龙舞狮', 'desc': '喜庆节日里的传统表演，祈求吉祥如意。'},
            {'id': 'yuanxiao', 'name': '元宵节', 'desc': '赏花灯、猜灯谜、吃元宵，春节的压轴大戏。'},
            {'id': 'zhongqiu', 'name': '中秋节', 'desc': '赏月、吃月饼，寄托团圆与思乡之情。'},
            {'id': 'chongyang', 'name': '重阳节', 'desc': '登高望远、敬老孝亲的传统节日。'},
        ],
    },
    {
        'id': 'arts',
        'name': '传统艺术与戏曲',
        'icon': '🎭',
        'color': '#8b1e8b',
        'bg_gradient': 'linear-gradient(135deg, #1b0e2d, #28104a)',
        'description': '领略中国传统艺术的精湛技艺，感受戏曲之美。',
        'items': [
            {'id': 'bianlian', 'name': '川剧变脸', 'desc': '四川川剧的绝技，瞬间变换脸谱令人惊叹。'},
            {'id': 'dunhuangbihua', 'name': '敦煌壁画', 'desc': '敦煌莫高窟的壁画艺术，丝路文明的瑰宝。'},
            {'id': 'erhu', 'name': '二胡', 'desc': '两根弦拉出千般情思，最具感染力的民族乐器。'},
            {'id': 'gongbi', 'name': '工笔花鸟画', 'desc': '精工细笔、栩栩如生的中国画技法的代表。'},
            {'id': 'guzheng', 'name': '古筝', 'desc': '清亮悠扬的弹拨乐器，高山流水遇知音。'},
            {'id': 'huangmei', 'name': '黄梅戏', 'desc': '安徽地方戏曲，唱腔优美婉转。'},
            {'id': 'jingju', 'name': '京剧', 'desc': '中国国粹，唱念做打、生旦净丑。'},
            {'id': 'kunqu', 'name': '昆曲', 'desc': '百戏之祖，中国最古老的剧种之一。'},
            {'id': 'pipa', 'name': '琵琶', 'desc': '大珠小珠落玉盘，弹拨乐器的王者。'},
            {'id': 'shanshui', 'name': '山水画', 'desc': '以山水为题材的中国画，意境深远。'},
            {'id': 'yueju', 'name': '粤剧', 'desc': '广东地方戏曲，岭南文化的代表。'},
        ],
    },
    {
        'id': 'crafts',
        'name': '非遗与传统工艺',
        'icon': '🏺',
        'color': '#1e7a8b',
        'bg_gradient': 'linear-gradient(135deg, #0e1b2d, #10284a)',
        'description': '触摸千年传承的非遗技艺，感受匠人匠心之美。',
        'items': [
            {'id': 'cixiu', 'name': '刺绣', 'desc': '一针一线绣出锦绣河山，中国女红的极致。'},
            {'id': 'jianzhi', 'name': '剪纸', 'desc': '一张红纸剪出万千世界，民间艺术的瑰宝。'},
            {'id': 'lianpu', 'name': '脸谱', 'desc': '京剧脸谱的色彩与图案，忠奸善恶一目了然。'},
            {'id': 'piying', 'name': '皮影', 'desc': '灯光下的剪影故事，古老的民间戏剧艺术。'},
            {'id': 'qinghua', 'name': '青花瓷', 'desc': '白底蓝花的瓷器，中国瓷器的经典代表。'},
            {'id': 'qingtong', 'name': '青铜器', 'desc': '夏商周时期的青铜文明，礼乐之器的辉煌。'},
            {'id': 'tangsancai', 'name': '唐三彩', 'desc': '唐代的彩色釉陶，丝绸之路的文化见证。'},
            {'id': 'tanghua', 'name': '糖画', 'desc': '以糖为墨、以勺为笔，甜蜜的民间艺术。'},
        ],
    },
    {
        'id': 'myths',
        'name': '神话传说与历史故事',
        'icon': '🐉',
        'color': '#c48a1e',
        'bg_gradient': 'linear-gradient(135deg, #2d200e, #4a3510)',
        'description': '走进古老的神话传说，聆听动人的历史故事。',
        'items': [
            {'id': 'change', 'name': '嫦娥奔月', 'desc': '嫦娥服下仙药飞向月宫，中秋佳节的美丽传说。'},
            {'id': 'danao', 'name': '大闹天宫', 'desc': '孙悟空大闹天宫，齐天大圣的传奇故事。'},
            {'id': 'fujing', 'name': '负荆请罪', 'desc': '廉颇负荆向蔺相如请罪，将相和的美谈。'},
            {'id': 'houyi', 'name': '后羿射日', 'desc': '后羿弯弓射九日，拯救苍生的英雄神话。'},
            {'id': 'jingwei', 'name': '精卫填海', 'desc': '精卫鸟衔石填海，坚韧不拔的精神象征。'},
            {'id': 'kongrong', 'name': '孔融让梨', 'desc': '孔融四岁让梨，谦让美德代代相传。'},
            {'id': 'niulang', 'name': '牛郎织女', 'desc': '七夕鹊桥相会，牛郎织女的爱情故事。'},
            {'id': 'nvwa', 'name': '女娲补天', 'desc': '女娲炼五色石补天，中华创世神话。'},
            {'id': 'pangu', 'name': '盘古开天', 'desc': '盘古开天辟地，混沌初开的创世神话。'},
            {'id': 'simaguang', 'name': '司马光砸缸', 'desc': '司马光砸缸救友，机智勇敢的少年故事。'},
        ],
    },
    {
        'id': 'food_clothing',
        'name': '饮食与服饰文化',
        'icon': '👘',
        'color': '#3a8b1e',
        'bg_gradient': 'linear-gradient(135deg, #0e2d1b, #104a28)',
        'description': '品味中华美食的千滋百味，欣赏传统服饰的华美。',
        'items': [
            {'id': 'jiaozi', 'name': '饺子', 'desc': '春节必备美食，形似元宝、寓意团圆富贵。'},
            {'id': 'yuebing', 'name': '月饼', 'desc': '中秋佳节的传统点心，象征团圆美满。'},
            {'id': 'zongzi', 'name': '粽子', 'desc': '端午节的时令美食，粽叶包裹的糯米香。'},
            {'id': 'tanghulu', 'name': '糖葫芦', 'desc': '红果串成串，裹上晶莹的冰糖，酸甜可口。'},
            {'id': 'tangyuan', 'name': '汤圆', 'desc': '元宵节必吃，软糯甜蜜，寓意团团圆圆。'},
            {'id': 'manhan', 'name': '满汉全席', 'desc': '清代宫廷盛宴，集满汉烹饪之大成。'},
            {'id': 'hanfu_ruqun', 'name': '汉服襦裙', 'desc': '上襦下裙的传统汉服，飘逸灵动之美。'},
            {'id': 'hanfu_quju', 'name': '汉服曲裾', 'desc': '交领右衽、曲裾深衣，汉代的经典服饰。'},
            {'id': 'tangzhuang', 'name': '唐装', 'desc': '由唐装演变而来的中式服装，端庄典雅。'},
            {'id': 'qipao', 'name': '旗袍', 'desc': '展现东方女性曲线美的经典服饰。'},
            {'id': 'miaozu', 'name': '苗族服饰', 'desc': '银饰璀璨、刺绣精美，苗族文化的瑰宝。'},
            {'id': 'zangzu', 'name': '藏族服饰', 'desc': '色彩鲜艳、配饰丰富，高原民族的独特着装。'},
            {'id': 'mengguzu', 'name': '蒙古族服饰', 'desc': '长袍腰带皮靴，草原游牧民族的服饰风格。'},
            {'id': 'fazan', 'name': '发簪', 'desc': '古代女子盘发点缀的精美饰物。'},
            {'id': 'yupei', 'name': '玉佩', 'desc': '君子无故玉不去身，温润典雅的配饰。'},
            {'id': 'xiangnang', 'name': '香囊', 'desc': '内装香料随身佩戴，芬芳四溢的雅物。'},
            {'id': 'hutouxie', 'name': '虎头鞋', 'desc': '婴儿穿的虎头形状布鞋，寓意驱邪保平安。'},
        ],
    },
    {
        'id': 'nature',
        'name': '自然与风物文化',
        'icon': '⛰️',
        'color': '#1e8b5a',
        'bg_gradient': 'linear-gradient(135deg, #0e2d1e, #104a35)',
        'description': '欣赏中华大地的壮美河山，品味雅致的风物文化。',
        'items': [
            {'id': 'huangshan', 'name': '黄山', 'desc': '五岳归来不看山，黄山归来不看岳。'},
            {'id': 'guilin', 'name': '桂林山水', 'desc': '桂林山水甲天下，山青水秀洞奇石美。'},
            {'id': 'xihu', 'name': '西湖', 'desc': '欲把西湖比西子，淡妆浓抹总相宜。'},
            {'id': 'zhangjiajie', 'name': '张家界', 'desc': '奇峰异石林立，宛如仙境的自然奇观。'},
            {'id': 'jiuzhaigou', 'name': '九寨沟', 'desc': '五彩斑斓的湖泊瀑布，人间仙境九寨沟。'},
            {'id': 'meilanzhuju', 'name': '梅兰竹菊', 'desc': '花中四君子，象征高洁品格的传统文化意象。'},
            {'id': 'mudan', 'name': '牡丹', 'desc': '唯有牡丹真国色，花开时节动京城。'},
            {'id': 'hehua', 'name': '荷花', 'desc': '出淤泥而不染，濯清涟而不妖。'},
            {'id': 'jinli', 'name': '锦鲤', 'desc': '色彩绚丽的观赏鱼，寓意富贵吉祥。'},
            {'id': 'xianhe', 'name': '仙鹤', 'desc': '延年益寿的祥瑞之鸟，松鹤延年的美好寓意。'},
            {'id': 'chaye', 'name': '茶叶', 'desc': '陆羽茶经传千年，中国茶文化的博大精深。'},
            {'id': 'sichou', 'name': '丝绸', 'desc': '丝绸之路的起点，中华文明的名片。'},
            {'id': 'ciqi', 'name': '瓷器', 'desc': 'China，瓷器与国同名的不朽传奇。'},
            {'id': 'wenfang', 'name': '文房四宝', 'desc': '笔墨纸砚，文人雅士书斋中的四件珍宝。'},
        ],
    },
]
