# Generated by Django 6.0.5 on 2026-05-28 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.CharField(max_length=50)),
                ('theme_name', models.CharField(max_length=50)),
                ('subtopic_id', models.CharField(max_length=50)),
                ('subtopic_name', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField()),
                ('time_spent', models.IntegerField()),
                ('moves', models.IntegerField()),
                ('hints_used', models.IntegerField(default=0)),
                ('score', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('avatar_data', models.TextField(blank=True, default='')),
                ('total_points', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('best_time', models.IntegerField(default=0)),
                ('best_moves', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EarnedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_id', models.CharField(max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reward_id')},
            },
        ),
    ]
