# Generated by Django 6.0.5 on 2026-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme_id", models.CharField(max_length=50, verbose_name="主题ID")),
                (
                    "theme_name",
                    models.CharField(max_length=100, verbose_name="主题名称"),
                ),
                ("difficulty", models.IntegerField(verbose_name="难度")),
                ("time_seconds", models.IntegerField(verbose_name="用时(秒)")),
                ("moves", models.IntegerField(verbose_name="步数")),
                ("hints_used", models.IntegerField(default=0, verbose_name="提示次数")),
                ("score", models.IntegerField(verbose_name="得分")),
                (
                    "culture_title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="文化标题"
                    ),
                ),
                (
                    "culture_content",
                    models.TextField(blank=True, default="", verbose_name="文化内容"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="完成时间"),
                ),
            ],
            options={
                "verbose_name": "游戏记录",
                "verbose_name_plural": "游戏记录",
                "ordering": ["-completed_at"],
            },
        ),
    ]
